# NETWORK SETTINGS

# use the light model?
light: True
# the base number of featres in every layer
ch: 32

# DATASET SETTINGS
dataset: matting_without_controlnet
batch_size: 1
img_size: (540,720)
img_ch: 3

# TRAINING SETTINGS
iteration: 1000000
# the frequency of saving the generated images
print_freq: 2000
# the frequency of saving the parameters
save_freq: 10000
train_length: 1898
decay_flag: True
# learning rate and weight decay
lr: 0.0001
weight_decay: 0.0001
# the ratio of the loss functions
adv_weight: 1
cycle_weight: 10
identity_weight: 10
cam_weight: 1000
# cuda and computing acceleration
cuda: True
benchmark_flag: True
# result dir
result_dir: logs
# resume Training?
resume: True
