[project]
name = "AnimeGAN-Converter"
version = "1.0.0"
description = ""
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "easydict==1.8",
    "moviepy==1.0.2",
    "onnxruntime==1.20.0",     # Install CPU on non-Windows
    "opencv-python==4.11.0.86",
    "socksio==1.0.0",
    "tqdm>=4.43.0",

    "pydantic==2.10.6",
    "tomli_w==1.2.0",
    "streamlit==1.43.2",
]
authors = [{ name = "MrXnneHang", email = "XnneHang@gmail.com" }]
keywords = []
license = { text = "MIT" }
classifiers = [
  "Operating System :: OS Independent",
  "License :: OSI Approved :: MIT License",
  "Typing :: Typed",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: Implementation :: CPython",
]

[dependency-groups]
dev = [
  "pyright>=1.1.391",
  "ruff>=0.9.3",
  "pytest>=8.3.4",
  "pytest-rerunfailures>=15.0",
]

[project.scripts]
converter = "converter.__main__:main"
test = "converter.test:main"

[tool.pyright]
include = ["src/converter"]
pythonVersion = "3.11"
typeCheckingMode = "strict"

[tool.hatch.build.targets.wheel]
packages = ["src/converter"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
